### ISSUE TITLE
please elaborate on README

### ISSUE THREAD

**Issue by DaPutzy** [Kein/Stalker2#1]
Hi, 

this looks like exactly what I'm looking for! However, i dont have a UE/Visual Studio/C++ background and im struggling with adding that enum. Im sure its very simple, i just cant seem to figure out how to do that.

Could you please elaborate on what you mean by "engine space"?

Thanks in advance :)

**Comment by Kein** [comment]
Still relevant?

**Comment by DaPutzy** [comment]
Got it working with the vanilla branch. 

Still think the README.md could be flashed out a bit regarding the custom engine stuff etc. but its your repo after all :)
